### ISSUE TITLE
Invalid username and passwords are not being caught in download_image()

### ISSUE THREAD

**Issue by cgmorton** [dgketchum/Landsat578#15]
If you have an incorrect username or password in the credentials file, the script is not catching that in download_image().  Instead it seems like the script is returning the invalid login HTML as a tgz file (~9KB).  You should be able to recreate this by transposing two letters in your password (at least that is how I found it...)

I think the issue is that the exact text string "You must sign in as a registered user to download data or place orders for USGS EROS products" (https://github.com/dgketchum/Landsat578/blob/master/landsat/usgs_download.py#L48) is not in the invalid login HTML.  The closest thing I am seeing is "sign in with your existing USGS registered username and password" or "Invalid username/password" (with a div id of "pageError" which might be easier to search for).

**Comment by dgketchum** [comment]
looking into this

**Comment by dgketchum** [comment]
should catch 'Invalid username/password' string in html response

**Comment by dgketchum** [comment]
still need a test for this

**Comment by nmgrluser** [comment]
use html status codes instead of trying to catch "invalid username/password" in the response

**Comment by cgmorton** [comment]
I thought I checked the status and it coming back as 200, but I could be mistaken.

**Comment by dgketchum** [comment]
yeah I found that response.status_code was 200 for this, so I updated the 'invalid ...' html string test

**Comment by dgketchum** [comment]
added a test for bad credentials exception handler
