### ISSUE TITLE
Current pip version (0.3.86) doesn't work for Python 2.7 on Windows

### ISSUE THREAD

**Issue by cgmorton** [dgketchum/Landsat578#22]
In a brand new Python 2.7 Conda environment on windows, a basic call to the landsat CLI raises the following ImportError.  It works fine for Python 3.6 though.  

```
(landsat-test) D:\>landsat
Traceback (most recent call last):
  File "c:\miniconda3\envs\pymetric\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\miniconda3\envs\pymetric\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Miniconda3\envs\pyMETRIC\Scripts\landsat.exe\__main__.py", line 5, in <module>
  File "c:\miniconda3\envs\pymetric\lib\site-packages\landsat\landsat.py", line 28, in <module>
    from landsat.download_composer import download_landsat
ImportError: No module named download_composer
```

Simplifying the download_landsat import block in landsat.py to the following line fixed the problem for me on both 2.7 and 3.6, but I didn't check to see if this breaks the tests or would work on mac/linux.
```
from .download_composer import download_landsat
```

I then changed the imports in download_composer.py to the following:
```
from .usgs_download import get_candidate_scenes_list, down_usgs_by_list
from .web_tools import convert_lat_lon_wrs2pr
```

Also, it seems like the v0.3.86 code on PyPi doesn't match the 0.3.86 release on Github and includes some of the code in the dev branch.

**Comment by dgketchum** [comment]
added future imports
