### ISSUE TITLE
could I get other files besides Geotiff file

### ISSUE THREAD

**Issue by moonlighf** [dgketchum/Landsat578#23]
could I get other files such as LandsatLook Natural Color Image and  QA file besides Geotiff file

**Comment by dgketchum** [comment]
This is only downloading the full-sized .tif files and there are no plans to expand the scope.  It will download the SCL-off path for Landsat 7 and the QA .tif for Landsat 8.
A good tool to use to get QuickLook images is with the [cloud free scene counts](https://github.com/Open-ET/cloud-free-scene-counts), a python tool that allows you to download the Landsat metadata, specify a location and time period, and download the QuickLook images according to that criteria.  The tool can be used to sort cloudy from clear scenes, and then create a clear scenes list, which can be used by Landsat578 to download  full-sized images.
