### ISSUE TITLE
Consider including 'pyarrow' and 'fastparquet' to setup.py

### ISSUE THREAD

**Issue by BrianY-Wang** [dgketchum/Landsat578#29]
when I ran landsat578 I had to pip install "pyarrow" and "fastparquet" manually. Maybe include it in the 'installs_requires' in line 59 of 'setup.py' ? 

like the following: 

`      install_requires=['pyyaml', 'pandas', 'requests', 'lxml', 'future','pyarrow', 'fastparquet'],`

**Comment by dgketchum** [comment]
Good call.

**Comment by dgketchum** [comment]
Made the commit to master
