### ISSUE TITLE
Output folder can't be a nested folder that doesn't exist

### ISSUE THREAD

**Issue by cgmorton** [dgketchum/Landsat578#3]
I'm assuming this is because the code is calling mkdir instead of makedirs (https://docs.python.org/2/library/os.html#os.makedirs)

I got the error when I tried setting the output to "-o .\landsat\foo\bar" where only the folder "landsat" was present.

**Comment by dgketchum** [comment]
good idea.  this is implemented.  i'm closing the issue.  i should push to pypi later today
