### ISSUE TITLE
Consider options for specifying download folder format

### ISSUE THREAD

**Issue by cgmorton** [dgketchum/Landsat578#4]
It would be nice to be able to control the folder structure where the images are saved.  For example, I would really like to have the images be saved by path, then row, then year (i.e. /43/30/2015), but I might also want to have them just be by path and row, similar to how they are saved in the Google Storage Bucket (https://console.cloud.google.com/storage/browser/gcp-public-data-landsat/LC08/01/043/033/), or maybe I want to use three digit path and row numbers for some reason (i.e. /043/030).

It probably wouldn't be pretty but you could allow the user to define a format string with specific key words.  Something like: "/{PATH:02d}/{ROW:02d}/{YEAR}" where the default could be what you currently have: "/{SENSOR}\_{PATH}\_{ROW}".

Just a thought.  Feel free to ignore!

**Comment by jirhiker** [comment]
consider using a config file for specifying more options. 
editing a config.yml file can be way easier than a ton of command line options

landstat.py --file /path/to/config.yml

**Comment by dgketchum** [comment]
yeah I was thinking about that

**Comment by dgketchum** [comment]
okay there is a config option to download clear_scenes.txt to the proper pymetric directory structure, in the interest of keeping the tool general, I'm avoiding adding formatting options beyond the native product  ID as an output folder/gzip in the location specified in --output
