### ISSUE TITLE
Landsat 7 images before July 11th can't be downloaded

### ISSUE THREAD

**Issue by cgmorton** [dgketchum/Landsat578#9]
The "all_in_one_pending" files (https://landsat.usgs.gov/landsat/all_in_one_pending_acquisition/L7/Pend_Acq/y1999/Jul/Jul-11-1999.txt) don't exist before July 11th, 1999, which means that Landsat 7 images between June 28th and July 10th can't be downloaded (I didn't see any L7 images before this in the metadata).  

This is a pretty minor issue (only 2 weeks of missing images) but it might be a good impetus for switching to using the bulk metadata XML (https://landsat.usgs.gov/download-entire-collection-metadata) like we talked about.  For a quick fix it might be possible to "write an exception handler that finds a future date and subtracts in 16-day increments".

**Comment by dgketchum** [comment]
xml working and tested, checking pre-July 11th download

**Comment by dgketchum** [comment]
xml data gives inconsistent results, e.g., 37, 27 won't pick up an image until July 12th, though 43, 30 will get an image at the end of June

**Comment by dgketchum** [comment]
in terms of 'all in one pending files', this bug is gone as we've switched to bulk metadata xml-based image search.  this is now picking up scenes from late june, 1999.
